### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "userId": 1,
  "symbol": "ASS",
  "side": "BUY",
  "price": 95.50,
  "quantity": 2.5
}

###

POST http://localhost:8080/api/orders
Content-Type: application/json

{
"userId": 1,
"symbol": "ASS",
"side": "SELL",
"price": 12345.4321234,
"quantity": 4
}

###

POST localhost:8080/api/users
Content-Type: application/json

{
  "username": "sdfgh",
  "email": "asdf@gmail.com",
  "password": "pass",
  "wallets": []
}

###

GET localhost:8080/api/users
###
DELETE localhost:8080/api/users/1

###

POST localhost:8080/api/wallets
Content-Type: application/json

{
  "user": {"id": 2},
  "availableAmount": 0,
  "blockedAmount": 0,
  "currency": "BTC/USDT"
}

###

POST localhost:8080/api/wallets/deposit
Content-Type: application/json

{
  "userId": 5,
  "currency": "BTC",
  "amount": 100000.12345
}

###

GET localhost:8080/api/wallets

###
DELETE localhost:8080/api/wallets/13
###

### 1. Andrei pune un ordin de CUMPĂRARE (BUY)
### El vrea 0.5 BTC la prețul de 95,000 USDT
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "user": {
    "id": 4
  },
  "symbol": "BTC/USDT",
  "side": "BUY",
  "price": 0,
  "quantity": 0.5
}

### PAUZĂ: În acest moment, verifică consola IntelliJ.
### Ar trebui să vezi: "📌 Ordin adăugat în Book (BIDS)".
### În DB: User 1 are 47,500 USDT blocați (0.5 * 95,000).

### 2. Bogdan pune un ordin de VÂNZARE (SELL)
### El vinde 0.5 BTC la același preț (95,000) - Match Instant!
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "user":{"id": 5},
  "symbol": "BTC/USDT",
  "side": "SELL",
  "price": 95000.00,
  "quantity": 2
}